// * DEFINE ALL THE ACTION TYPES //
export const UserActions = {
  LOAD_USER: 'LOAD_USER',
  SET_USER_INFORMATION: 'SET_USER_INFORMATION',
  UPDATE_USER_INFROMATION: 'UPDATE_USER_INFROMATION',
  REMOVE_USER_INFORMATION: 'REMOVE_USER_INFORMATION'
}

export const StockActions = {
  SET_STOCK_DETAILS: "SET_STOCK_DETAILS",
  ADD_STOCK: "ADD_STOCK",
  UPDATE_STOCK: "UPDATE_STOCK",
  STOCK_BULK_REMOVE: "STOCK_BULK_REMOVE"
}

export const WeeklySamplingActions = {
  SET_WEEKLY_SAMPLING: "SET_WEEKLY_SAMPLING",
  ADD_WEEKLY_SAMPLING: "ADD_WEEKLY_SAMPLING",
  UPDATE_WEEKLY_SAMPLING: "UPDATE_WEEKLY_SAMPLING",
  REMOVE_WEEKLY_SAMPLING: "REMOVE_WEEKLY_SAMPLING"
}

export const WeeklyApplicationsActions = {
  SET_WEEKLY_APPLICATION: "SET_WEEKLY_APPLICATION",
  ADD_WEEKLY_APPLICATION: "ADD_WEEKLY_APPLICATION",
  UPDATE_WEEKLY_APPLICATION: "UPDATE_WEEKLY_APPLICATION",
  REMOVE_WEEKLY_APPLICATION: "REMOVE_WEEKLY_APPLICATION"
}

export const SalesPriceActions = {
  SET_SALES_PRICE: "SET_SALES_PRICE",
  ADD_SALES_PRICE: "ADD_SALES_PRICE",
  UPDATE_SALES_PRICE: "UPDATE_SALES_PRICE",
  REMOVE_SALES_PRICE: "REMOVE_SALES_PRICE"
}

export const ApplicationActions = {
  SET_APPLICATION: "SET_APPLICATION",
  ADD_APPLICATION: "ADD_APPLICATION",
  UPDATE_APPLICATION: "UPDATE_APPLICATION",
  REMOVE_APPLICATION: "REMOVE_APPLICATION"
}

export const ClubMemberActions = {
  SET_CLUB_MEMBER: "SET_CLUB_MEMBER",
  ADD_CLUB_MEMBER: "ADD_CLUB_MEMBER",
  UPDATE_CLUB_MEMBER: "UPDATE_CLUB_MEMBER",
  REMOVE_CLUB_MEMBER: "REMOVE_CLUB_MEMBER"
}

export const DailyFeedActions = {
  SET_DAILY_FEED: "SET_DAILY_FEED",
  ADD_DAILY_FEED: "ADD_DAILY_FEED",
  UPDATE_DAILY_FEED: "UPDATE_DAILY_FEED",
  REMOVE_DAILY_FEED: "REMOVE_DAILY_FEED"
}

export const FarmActions = {
  SET_FARM: "SET_FARM",
  ADD_FARM: "ADD_FARM",
  UPDATE_FARM: "UPDATE_FARM",
  REMOVE_FARM: "REMOVE_FARM"
}

export const HarvestActions = {
  SET_HARVEST: "SET_HARVEST",
  ADD_HARVEST: "ADD_HARVEST",
  UPDATE_HARVEST: "UPDATE_HARVEST",
  REMOVE_HARVEST: "REMOVE_HARVEST"
}